### ISSUE TITLE
out of memory during training

### ISSUE THREAD

**Issue by ginobilinie** [HuguesTHOMAS/KPConv-PyTorch#24]
Hi Hugues,

I'm currently running some experiments with this repository on NPM3D. However, I found part of the experiments will exit automatically because of out-of-memory issue during training. I have checked the code, but I donot have any idea about it now. Have you encountered similar cases? Have you got any suggestions about it?

Here is some snapshot:

...
e007-i0009 => L=3.165 acc= 91% / t(ms): 122.0 120.0  61.5)
Traceback (most recent call last):
  File "train_dist_NPM3D.py", line 349, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "/home/dongnie/codebooks/KPConv-PyTorch/utils/trainer_dist.py", line 212, in train
    loss.backward()
  File "/home/dongnie/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/dongnie/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 3.36 GiB (GPU 2; 10.73 GiB total capacity; 3.70 GiB already allocated; 3.14 GiB free; 6.81 GiB reserved in total by PyTorch) (malloc at /opt/conda/conda-bld/pytorch_1591914742272/work/c10/cuda/CUDACachingAllocator.cpp:289)

Thanks.

**Comment by HuguesTHOMAS** [comment]
Have you tried to reduce the `in_radius` or increase the `first subsampling_dl` ??

**Comment by ginobilinie** [comment]
I haven't try it yet. I'll try it today. Thanks very much.

**Comment by FengqiLiu1221** [comment]
> I haven't try it yet. I'll try it today. Thanks very much.

I have tried to reduce the in_radius , increase the first subsampling_dl and reduce the batchsize, however，it doesn't work!

**Comment by HuguesTHOMAS** [comment]
Do you mean you still have a `CUDA out of memory` error?

What GPU are you using?

**Comment by FengqiLiu1221** [comment]
I have solved it. Thanks a lot!

**Comment by ginobilinie** [comment]
> I have solved it. Thanks a lot!

How do you solve it?

**Comment by ginobilinie** [comment]
@FengqiLiu1221 Can you please share how you solve it?

**Comment by universitypengyuyan** [comment]
> 我已经解决了。多谢！

Can you share your solution? Thank you very much.
